---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
spec:
  type: ClusterIP 
  ports:
    - name: http
      port: {{ .Values.app.port }}
      targetPort: 8080
  selector:
    app: {{ .Values.app.name }}
